package me.eddiep.android.voting.data;

import android.app.Activity;
import android.content.Context;
import android.graphics.Typeface;
import android.graphics.drawable.Drawable;
import android.os.Build;
import android.support.design.widget.FloatingActionButton;
import android.support.v4.content.ContextCompat;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.TextView;

import java.util.List;

import me.eddiep.android.voting.R;

public class CandidateListAdapter extends ArrayAdapter<Candidate> {
    private LayoutInflater vi;
    private Activity owner;
    private Typeface bold;
    private Typeface light;

    public CandidateListAdapter(Context context, List<Candidate> elections, Activity owner) {
        super(context, -1, elections);

        vi = LayoutInflater.from(context);
        this.owner = owner;

        bold = Typeface.createFromAsset(context.getAssets(), "GOTHAM-BOLD.TTF");
        light = Typeface.createFromAsset(context.getAssets(), "GOTHAM-LIGHT.TTF");
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        View v = convertView;
        ViewHolder holder;

        if (v == null) {
            v = vi.inflate(R.layout.candidate_item, parent, false);
        }

        if (v.getTag() != null) {
            holder = (ViewHolder)v.getTag();
        } else {
            holder = new ViewHolder();
            holder.name = (TextView) v.findViewById(R.id.candidateName);
            holder.party = (TextView) v.findViewById(R.id.candidateParty);
            holder.background = (ImageView) v.findViewById(R.id.candidateProfile);

            v.setTag(holder);
        }

        final Candidate candidate = getItem(position);
        if (candidate != null) {
            Drawable d = getDrawable(owner, candidate.getBackground());
            holder.background.setImageDrawable(d);

            holder.name.setText(candidate.getName());
            holder.party.setText(candidate.getParty());
        }

        return v;
    }

    /**
     * Return a drawable object associated with a particular resource ID.
     * <p>
     * Starting in {@link android.os.Build.VERSION_CODES#LOLLIPOP}, the returned
     * drawable will be styled for the specified Context's theme.
     *
     * @param id The desired resource identifier, as generated by the aapt tool.
     *            This integer encodes the package, type, and resource entry.
     *            The value 0 is an invalid identifier.
     * @return Drawable An object that can be used to draw this resource.
     */
    public final Drawable getDrawable(Context context, int id) {
        final int version = Build.VERSION.SDK_INT;
        if (version >= 21) {
            return ContextCompat.getDrawable(context, id);
        } else {
            return context.getResources().getDrawable(id);
        }
    }

    static class ViewHolder {
        TextView name;
        TextView party;
        ImageView background;
    }
}
